// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mds.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mds_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_mds_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mds_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mds_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mds_2eproto;
namespace fs {
namespace mds {
class CreateFileRequest;
class CreateFileRequestDefaultTypeInternal;
extern CreateFileRequestDefaultTypeInternal _CreateFileRequest_default_instance_;
class CreateFileResponse;
class CreateFileResponseDefaultTypeInternal;
extern CreateFileResponseDefaultTypeInternal _CreateFileResponse_default_instance_;
class GetBlockInfoRequest;
class GetBlockInfoRequestDefaultTypeInternal;
extern GetBlockInfoRequestDefaultTypeInternal _GetBlockInfoRequest_default_instance_;
class GetBlockInfoResponse;
class GetBlockInfoResponseDefaultTypeInternal;
extern GetBlockInfoResponseDefaultTypeInternal _GetBlockInfoResponse_default_instance_;
class LookupRequest;
class LookupRequestDefaultTypeInternal;
extern LookupRequestDefaultTypeInternal _LookupRequest_default_instance_;
class LookupResponse;
class LookupResponseDefaultTypeInternal;
extern LookupResponseDefaultTypeInternal _LookupResponse_default_instance_;
class RegisterNodeRequest;
class RegisterNodeRequestDefaultTypeInternal;
extern RegisterNodeRequestDefaultTypeInternal _RegisterNodeRequest_default_instance_;
class RegisterNodeResponse;
class RegisterNodeResponseDefaultTypeInternal;
extern RegisterNodeResponseDefaultTypeInternal _RegisterNodeResponse_default_instance_;
}  // namespace mds
}  // namespace fs
PROTOBUF_NAMESPACE_OPEN
template<> ::fs::mds::CreateFileRequest* Arena::CreateMaybeMessage<::fs::mds::CreateFileRequest>(Arena*);
template<> ::fs::mds::CreateFileResponse* Arena::CreateMaybeMessage<::fs::mds::CreateFileResponse>(Arena*);
template<> ::fs::mds::GetBlockInfoRequest* Arena::CreateMaybeMessage<::fs::mds::GetBlockInfoRequest>(Arena*);
template<> ::fs::mds::GetBlockInfoResponse* Arena::CreateMaybeMessage<::fs::mds::GetBlockInfoResponse>(Arena*);
template<> ::fs::mds::LookupRequest* Arena::CreateMaybeMessage<::fs::mds::LookupRequest>(Arena*);
template<> ::fs::mds::LookupResponse* Arena::CreateMaybeMessage<::fs::mds::LookupResponse>(Arena*);
template<> ::fs::mds::RegisterNodeRequest* Arena::CreateMaybeMessage<::fs::mds::RegisterNodeRequest>(Arena*);
template<> ::fs::mds::RegisterNodeResponse* Arena::CreateMaybeMessage<::fs::mds::RegisterNodeResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace fs {
namespace mds {

// ===================================================================

class RegisterNodeRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fs.mds.RegisterNodeRequest) */ {
 public:
  inline RegisterNodeRequest() : RegisterNodeRequest(nullptr) {};
  virtual ~RegisterNodeRequest();

  RegisterNodeRequest(const RegisterNodeRequest& from);
  RegisterNodeRequest(RegisterNodeRequest&& from) noexcept
    : RegisterNodeRequest() {
    *this = ::std::move(from);
  }

  inline RegisterNodeRequest& operator=(const RegisterNodeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RegisterNodeRequest& operator=(RegisterNodeRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RegisterNodeRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RegisterNodeRequest* internal_default_instance() {
    return reinterpret_cast<const RegisterNodeRequest*>(
               &_RegisterNodeRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RegisterNodeRequest& a, RegisterNodeRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(RegisterNodeRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RegisterNodeRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RegisterNodeRequest* New() const final {
    return CreateMaybeMessage<RegisterNodeRequest>(nullptr);
  }

  RegisterNodeRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RegisterNodeRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RegisterNodeRequest& from);
  void MergeFrom(const RegisterNodeRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RegisterNodeRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fs.mds.RegisterNodeRequest";
  }
  protected:
  explicit RegisterNodeRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mds_2eproto);
    return ::descriptor_table_mds_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVolumeIdsFieldNumber = 2,
    kAddressFieldNumber = 1,
  };
  // repeated string volume_ids = 2;
  int volume_ids_size() const;
  private:
  int _internal_volume_ids_size() const;
  public:
  void clear_volume_ids();
  const std::string& volume_ids(int index) const;
  std::string* mutable_volume_ids(int index);
  void set_volume_ids(int index, const std::string& value);
  void set_volume_ids(int index, std::string&& value);
  void set_volume_ids(int index, const char* value);
  void set_volume_ids(int index, const char* value, size_t size);
  std::string* add_volume_ids();
  void add_volume_ids(const std::string& value);
  void add_volume_ids(std::string&& value);
  void add_volume_ids(const char* value);
  void add_volume_ids(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& volume_ids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_volume_ids();
  private:
  const std::string& _internal_volume_ids(int index) const;
  std::string* _internal_add_volume_ids();
  public:

  // string address = 1;
  void clear_address();
  const std::string& address() const;
  void set_address(const std::string& value);
  void set_address(std::string&& value);
  void set_address(const char* value);
  void set_address(const char* value, size_t size);
  std::string* mutable_address();
  std::string* release_address();
  void set_allocated_address(std::string* address);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_address();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_address(
      std::string* address);
  private:
  const std::string& _internal_address() const;
  void _internal_set_address(const std::string& value);
  std::string* _internal_mutable_address();
  public:

  // @@protoc_insertion_point(class_scope:fs.mds.RegisterNodeRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> volume_ids_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr address_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mds_2eproto;
};
// -------------------------------------------------------------------

class RegisterNodeResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fs.mds.RegisterNodeResponse) */ {
 public:
  inline RegisterNodeResponse() : RegisterNodeResponse(nullptr) {};
  virtual ~RegisterNodeResponse();

  RegisterNodeResponse(const RegisterNodeResponse& from);
  RegisterNodeResponse(RegisterNodeResponse&& from) noexcept
    : RegisterNodeResponse() {
    *this = ::std::move(from);
  }

  inline RegisterNodeResponse& operator=(const RegisterNodeResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline RegisterNodeResponse& operator=(RegisterNodeResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RegisterNodeResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RegisterNodeResponse* internal_default_instance() {
    return reinterpret_cast<const RegisterNodeResponse*>(
               &_RegisterNodeResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RegisterNodeResponse& a, RegisterNodeResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(RegisterNodeResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RegisterNodeResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RegisterNodeResponse* New() const final {
    return CreateMaybeMessage<RegisterNodeResponse>(nullptr);
  }

  RegisterNodeResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RegisterNodeResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RegisterNodeResponse& from);
  void MergeFrom(const RegisterNodeResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RegisterNodeResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fs.mds.RegisterNodeResponse";
  }
  protected:
  explicit RegisterNodeResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mds_2eproto);
    return ::descriptor_table_mds_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusFieldNumber = 1,
  };
  // .fs.common.StatusCode status = 1;
  void clear_status();
  ::fs::common::StatusCode status() const;
  void set_status(::fs::common::StatusCode value);
  private:
  ::fs::common::StatusCode _internal_status() const;
  void _internal_set_status(::fs::common::StatusCode value);
  public:

  // @@protoc_insertion_point(class_scope:fs.mds.RegisterNodeResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mds_2eproto;
};
// -------------------------------------------------------------------

class CreateFileRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fs.mds.CreateFileRequest) */ {
 public:
  inline CreateFileRequest() : CreateFileRequest(nullptr) {};
  virtual ~CreateFileRequest();

  CreateFileRequest(const CreateFileRequest& from);
  CreateFileRequest(CreateFileRequest&& from) noexcept
    : CreateFileRequest() {
    *this = ::std::move(from);
  }

  inline CreateFileRequest& operator=(const CreateFileRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreateFileRequest& operator=(CreateFileRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CreateFileRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CreateFileRequest* internal_default_instance() {
    return reinterpret_cast<const CreateFileRequest*>(
               &_CreateFileRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CreateFileRequest& a, CreateFileRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(CreateFileRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreateFileRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CreateFileRequest* New() const final {
    return CreateMaybeMessage<CreateFileRequest>(nullptr);
  }

  CreateFileRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CreateFileRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CreateFileRequest& from);
  void MergeFrom(const CreateFileRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreateFileRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fs.mds.CreateFileRequest";
  }
  protected:
  explicit CreateFileRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mds_2eproto);
    return ::descriptor_table_mds_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPathFieldNumber = 1,
    kModeFieldNumber = 2,
  };
  // string path = 1;
  void clear_path();
  const std::string& path() const;
  void set_path(const std::string& value);
  void set_path(std::string&& value);
  void set_path(const char* value);
  void set_path(const char* value, size_t size);
  std::string* mutable_path();
  std::string* release_path();
  void set_allocated_path(std::string* path);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_path();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_path(
      std::string* path);
  private:
  const std::string& _internal_path() const;
  void _internal_set_path(const std::string& value);
  std::string* _internal_mutable_path();
  public:

  // int32 mode = 2;
  void clear_mode();
  ::PROTOBUF_NAMESPACE_ID::int32 mode() const;
  void set_mode(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_mode() const;
  void _internal_set_mode(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:fs.mds.CreateFileRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_;
  ::PROTOBUF_NAMESPACE_ID::int32 mode_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mds_2eproto;
};
// -------------------------------------------------------------------

class CreateFileResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fs.mds.CreateFileResponse) */ {
 public:
  inline CreateFileResponse() : CreateFileResponse(nullptr) {};
  virtual ~CreateFileResponse();

  CreateFileResponse(const CreateFileResponse& from);
  CreateFileResponse(CreateFileResponse&& from) noexcept
    : CreateFileResponse() {
    *this = ::std::move(from);
  }

  inline CreateFileResponse& operator=(const CreateFileResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreateFileResponse& operator=(CreateFileResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CreateFileResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CreateFileResponse* internal_default_instance() {
    return reinterpret_cast<const CreateFileResponse*>(
               &_CreateFileResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(CreateFileResponse& a, CreateFileResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(CreateFileResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreateFileResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CreateFileResponse* New() const final {
    return CreateMaybeMessage<CreateFileResponse>(nullptr);
  }

  CreateFileResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CreateFileResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CreateFileResponse& from);
  void MergeFrom(const CreateFileResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreateFileResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fs.mds.CreateFileResponse";
  }
  protected:
  explicit CreateFileResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mds_2eproto);
    return ::descriptor_table_mds_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInodeIdFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // uint64 inode_id = 2;
  void clear_inode_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 inode_id() const;
  void set_inode_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_inode_id() const;
  void _internal_set_inode_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // .fs.common.StatusCode status = 1;
  void clear_status();
  ::fs::common::StatusCode status() const;
  void set_status(::fs::common::StatusCode value);
  private:
  ::fs::common::StatusCode _internal_status() const;
  void _internal_set_status(::fs::common::StatusCode value);
  public:

  // @@protoc_insertion_point(class_scope:fs.mds.CreateFileResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint64 inode_id_;
  int status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mds_2eproto;
};
// -------------------------------------------------------------------

class LookupRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fs.mds.LookupRequest) */ {
 public:
  inline LookupRequest() : LookupRequest(nullptr) {};
  virtual ~LookupRequest();

  LookupRequest(const LookupRequest& from);
  LookupRequest(LookupRequest&& from) noexcept
    : LookupRequest() {
    *this = ::std::move(from);
  }

  inline LookupRequest& operator=(const LookupRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline LookupRequest& operator=(LookupRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LookupRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LookupRequest* internal_default_instance() {
    return reinterpret_cast<const LookupRequest*>(
               &_LookupRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(LookupRequest& a, LookupRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(LookupRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LookupRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LookupRequest* New() const final {
    return CreateMaybeMessage<LookupRequest>(nullptr);
  }

  LookupRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LookupRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LookupRequest& from);
  void MergeFrom(const LookupRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LookupRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fs.mds.LookupRequest";
  }
  protected:
  explicit LookupRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mds_2eproto);
    return ::descriptor_table_mds_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPathFieldNumber = 1,
  };
  // string path = 1;
  void clear_path();
  const std::string& path() const;
  void set_path(const std::string& value);
  void set_path(std::string&& value);
  void set_path(const char* value);
  void set_path(const char* value, size_t size);
  std::string* mutable_path();
  std::string* release_path();
  void set_allocated_path(std::string* path);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_path();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_path(
      std::string* path);
  private:
  const std::string& _internal_path() const;
  void _internal_set_path(const std::string& value);
  std::string* _internal_mutable_path();
  public:

  // @@protoc_insertion_point(class_scope:fs.mds.LookupRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mds_2eproto;
};
// -------------------------------------------------------------------

class LookupResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fs.mds.LookupResponse) */ {
 public:
  inline LookupResponse() : LookupResponse(nullptr) {};
  virtual ~LookupResponse();

  LookupResponse(const LookupResponse& from);
  LookupResponse(LookupResponse&& from) noexcept
    : LookupResponse() {
    *this = ::std::move(from);
  }

  inline LookupResponse& operator=(const LookupResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline LookupResponse& operator=(LookupResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LookupResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LookupResponse* internal_default_instance() {
    return reinterpret_cast<const LookupResponse*>(
               &_LookupResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(LookupResponse& a, LookupResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(LookupResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LookupResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LookupResponse* New() const final {
    return CreateMaybeMessage<LookupResponse>(nullptr);
  }

  LookupResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LookupResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LookupResponse& from);
  void MergeFrom(const LookupResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LookupResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fs.mds.LookupResponse";
  }
  protected:
  explicit LookupResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mds_2eproto);
    return ::descriptor_table_mds_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInodeIdFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // uint64 inode_id = 2;
  void clear_inode_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 inode_id() const;
  void set_inode_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_inode_id() const;
  void _internal_set_inode_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // .fs.common.StatusCode status = 1;
  void clear_status();
  ::fs::common::StatusCode status() const;
  void set_status(::fs::common::StatusCode value);
  private:
  ::fs::common::StatusCode _internal_status() const;
  void _internal_set_status(::fs::common::StatusCode value);
  public:

  // @@protoc_insertion_point(class_scope:fs.mds.LookupResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint64 inode_id_;
  int status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mds_2eproto;
};
// -------------------------------------------------------------------

class GetBlockInfoRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fs.mds.GetBlockInfoRequest) */ {
 public:
  inline GetBlockInfoRequest() : GetBlockInfoRequest(nullptr) {};
  virtual ~GetBlockInfoRequest();

  GetBlockInfoRequest(const GetBlockInfoRequest& from);
  GetBlockInfoRequest(GetBlockInfoRequest&& from) noexcept
    : GetBlockInfoRequest() {
    *this = ::std::move(from);
  }

  inline GetBlockInfoRequest& operator=(const GetBlockInfoRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetBlockInfoRequest& operator=(GetBlockInfoRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetBlockInfoRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetBlockInfoRequest* internal_default_instance() {
    return reinterpret_cast<const GetBlockInfoRequest*>(
               &_GetBlockInfoRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(GetBlockInfoRequest& a, GetBlockInfoRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetBlockInfoRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetBlockInfoRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetBlockInfoRequest* New() const final {
    return CreateMaybeMessage<GetBlockInfoRequest>(nullptr);
  }

  GetBlockInfoRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetBlockInfoRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetBlockInfoRequest& from);
  void MergeFrom(const GetBlockInfoRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetBlockInfoRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fs.mds.GetBlockInfoRequest";
  }
  protected:
  explicit GetBlockInfoRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mds_2eproto);
    return ::descriptor_table_mds_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInodeIdFieldNumber = 1,
    kFileOffsetFieldNumber = 2,
    kIsWriteFieldNumber = 3,
  };
  // uint64 inode_id = 1;
  void clear_inode_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 inode_id() const;
  void set_inode_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_inode_id() const;
  void _internal_set_inode_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 file_offset = 2;
  void clear_file_offset();
  ::PROTOBUF_NAMESPACE_ID::uint64 file_offset() const;
  void set_file_offset(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_file_offset() const;
  void _internal_set_file_offset(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // bool is_write = 3;
  void clear_is_write();
  bool is_write() const;
  void set_is_write(bool value);
  private:
  bool _internal_is_write() const;
  void _internal_set_is_write(bool value);
  public:

  // @@protoc_insertion_point(class_scope:fs.mds.GetBlockInfoRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint64 inode_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 file_offset_;
  bool is_write_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mds_2eproto;
};
// -------------------------------------------------------------------

class GetBlockInfoResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fs.mds.GetBlockInfoResponse) */ {
 public:
  inline GetBlockInfoResponse() : GetBlockInfoResponse(nullptr) {};
  virtual ~GetBlockInfoResponse();

  GetBlockInfoResponse(const GetBlockInfoResponse& from);
  GetBlockInfoResponse(GetBlockInfoResponse&& from) noexcept
    : GetBlockInfoResponse() {
    *this = ::std::move(from);
  }

  inline GetBlockInfoResponse& operator=(const GetBlockInfoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetBlockInfoResponse& operator=(GetBlockInfoResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetBlockInfoResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetBlockInfoResponse* internal_default_instance() {
    return reinterpret_cast<const GetBlockInfoResponse*>(
               &_GetBlockInfoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(GetBlockInfoResponse& a, GetBlockInfoResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetBlockInfoResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetBlockInfoResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetBlockInfoResponse* New() const final {
    return CreateMaybeMessage<GetBlockInfoResponse>(nullptr);
  }

  GetBlockInfoResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetBlockInfoResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetBlockInfoResponse& from);
  void MergeFrom(const GetBlockInfoResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetBlockInfoResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fs.mds.GetBlockInfoResponse";
  }
  protected:
  explicit GetBlockInfoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mds_2eproto);
    return ::descriptor_table_mds_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStorageAddrFieldNumber = 2,
    kVolumeIdFieldNumber = 3,
    kBlockOffsetFieldNumber = 4,
    kBlockLengthFieldNumber = 5,
    kStatusFieldNumber = 1,
  };
  // string storage_addr = 2;
  void clear_storage_addr();
  const std::string& storage_addr() const;
  void set_storage_addr(const std::string& value);
  void set_storage_addr(std::string&& value);
  void set_storage_addr(const char* value);
  void set_storage_addr(const char* value, size_t size);
  std::string* mutable_storage_addr();
  std::string* release_storage_addr();
  void set_allocated_storage_addr(std::string* storage_addr);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_storage_addr();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_storage_addr(
      std::string* storage_addr);
  private:
  const std::string& _internal_storage_addr() const;
  void _internal_set_storage_addr(const std::string& value);
  std::string* _internal_mutable_storage_addr();
  public:

  // uint64 volume_id = 3;
  void clear_volume_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 volume_id() const;
  void set_volume_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_volume_id() const;
  void _internal_set_volume_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 block_offset = 4;
  void clear_block_offset();
  ::PROTOBUF_NAMESPACE_ID::uint64 block_offset() const;
  void set_block_offset(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_block_offset() const;
  void _internal_set_block_offset(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 block_length = 5;
  void clear_block_length();
  ::PROTOBUF_NAMESPACE_ID::uint64 block_length() const;
  void set_block_length(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_block_length() const;
  void _internal_set_block_length(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // .fs.common.StatusCode status = 1;
  void clear_status();
  ::fs::common::StatusCode status() const;
  void set_status(::fs::common::StatusCode value);
  private:
  ::fs::common::StatusCode _internal_status() const;
  void _internal_set_status(::fs::common::StatusCode value);
  public:

  // @@protoc_insertion_point(class_scope:fs.mds.GetBlockInfoResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr storage_addr_;
  ::PROTOBUF_NAMESPACE_ID::uint64 volume_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 block_offset_;
  ::PROTOBUF_NAMESPACE_ID::uint64 block_length_;
  int status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mds_2eproto;
};
// ===================================================================

class MdsService_Stub;

class MdsService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline MdsService() {};
 public:
  virtual ~MdsService();

  typedef MdsService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void RegisterNode(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::fs::mds::RegisterNodeRequest* request,
                       ::fs::mds::RegisterNodeResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void CreateFile(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::fs::mds::CreateFileRequest* request,
                       ::fs::mds::CreateFileResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void Lookup(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::fs::mds::LookupRequest* request,
                       ::fs::mds::LookupResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void GetBlockInfo(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::fs::mds::GetBlockInfoRequest* request,
                       ::fs::mds::GetBlockInfoResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(MdsService);
};

class MdsService_Stub : public MdsService {
 public:
  MdsService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  MdsService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~MdsService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements MdsService ------------------------------------------

  void RegisterNode(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::fs::mds::RegisterNodeRequest* request,
                       ::fs::mds::RegisterNodeResponse* response,
                       ::google::protobuf::Closure* done);
  void CreateFile(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::fs::mds::CreateFileRequest* request,
                       ::fs::mds::CreateFileResponse* response,
                       ::google::protobuf::Closure* done);
  void Lookup(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::fs::mds::LookupRequest* request,
                       ::fs::mds::LookupResponse* response,
                       ::google::protobuf::Closure* done);
  void GetBlockInfo(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::fs::mds::GetBlockInfoRequest* request,
                       ::fs::mds::GetBlockInfoResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(MdsService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RegisterNodeRequest

// string address = 1;
inline void RegisterNodeRequest::clear_address() {
  address_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& RegisterNodeRequest::address() const {
  // @@protoc_insertion_point(field_get:fs.mds.RegisterNodeRequest.address)
  return _internal_address();
}
inline void RegisterNodeRequest::set_address(const std::string& value) {
  _internal_set_address(value);
  // @@protoc_insertion_point(field_set:fs.mds.RegisterNodeRequest.address)
}
inline std::string* RegisterNodeRequest::mutable_address() {
  // @@protoc_insertion_point(field_mutable:fs.mds.RegisterNodeRequest.address)
  return _internal_mutable_address();
}
inline const std::string& RegisterNodeRequest::_internal_address() const {
  return address_.Get();
}
inline void RegisterNodeRequest::_internal_set_address(const std::string& value) {
  
  address_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void RegisterNodeRequest::set_address(std::string&& value) {
  
  address_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:fs.mds.RegisterNodeRequest.address)
}
inline void RegisterNodeRequest::set_address(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  address_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:fs.mds.RegisterNodeRequest.address)
}
inline void RegisterNodeRequest::set_address(const char* value,
    size_t size) {
  
  address_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:fs.mds.RegisterNodeRequest.address)
}
inline std::string* RegisterNodeRequest::_internal_mutable_address() {
  
  return address_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* RegisterNodeRequest::release_address() {
  // @@protoc_insertion_point(field_release:fs.mds.RegisterNodeRequest.address)
  return address_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RegisterNodeRequest::set_allocated_address(std::string* address) {
  if (address != nullptr) {
    
  } else {
    
  }
  address_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), address,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:fs.mds.RegisterNodeRequest.address)
}
inline std::string* RegisterNodeRequest::unsafe_arena_release_address() {
  // @@protoc_insertion_point(field_unsafe_arena_release:fs.mds.RegisterNodeRequest.address)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return address_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void RegisterNodeRequest::unsafe_arena_set_allocated_address(
    std::string* address) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (address != nullptr) {
    
  } else {
    
  }
  address_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      address, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:fs.mds.RegisterNodeRequest.address)
}

// repeated string volume_ids = 2;
inline int RegisterNodeRequest::_internal_volume_ids_size() const {
  return volume_ids_.size();
}
inline int RegisterNodeRequest::volume_ids_size() const {
  return _internal_volume_ids_size();
}
inline void RegisterNodeRequest::clear_volume_ids() {
  volume_ids_.Clear();
}
inline std::string* RegisterNodeRequest::add_volume_ids() {
  // @@protoc_insertion_point(field_add_mutable:fs.mds.RegisterNodeRequest.volume_ids)
  return _internal_add_volume_ids();
}
inline const std::string& RegisterNodeRequest::_internal_volume_ids(int index) const {
  return volume_ids_.Get(index);
}
inline const std::string& RegisterNodeRequest::volume_ids(int index) const {
  // @@protoc_insertion_point(field_get:fs.mds.RegisterNodeRequest.volume_ids)
  return _internal_volume_ids(index);
}
inline std::string* RegisterNodeRequest::mutable_volume_ids(int index) {
  // @@protoc_insertion_point(field_mutable:fs.mds.RegisterNodeRequest.volume_ids)
  return volume_ids_.Mutable(index);
}
inline void RegisterNodeRequest::set_volume_ids(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:fs.mds.RegisterNodeRequest.volume_ids)
  volume_ids_.Mutable(index)->assign(value);
}
inline void RegisterNodeRequest::set_volume_ids(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:fs.mds.RegisterNodeRequest.volume_ids)
  volume_ids_.Mutable(index)->assign(std::move(value));
}
inline void RegisterNodeRequest::set_volume_ids(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  volume_ids_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:fs.mds.RegisterNodeRequest.volume_ids)
}
inline void RegisterNodeRequest::set_volume_ids(int index, const char* value, size_t size) {
  volume_ids_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:fs.mds.RegisterNodeRequest.volume_ids)
}
inline std::string* RegisterNodeRequest::_internal_add_volume_ids() {
  return volume_ids_.Add();
}
inline void RegisterNodeRequest::add_volume_ids(const std::string& value) {
  volume_ids_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:fs.mds.RegisterNodeRequest.volume_ids)
}
inline void RegisterNodeRequest::add_volume_ids(std::string&& value) {
  volume_ids_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:fs.mds.RegisterNodeRequest.volume_ids)
}
inline void RegisterNodeRequest::add_volume_ids(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  volume_ids_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:fs.mds.RegisterNodeRequest.volume_ids)
}
inline void RegisterNodeRequest::add_volume_ids(const char* value, size_t size) {
  volume_ids_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:fs.mds.RegisterNodeRequest.volume_ids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
RegisterNodeRequest::volume_ids() const {
  // @@protoc_insertion_point(field_list:fs.mds.RegisterNodeRequest.volume_ids)
  return volume_ids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
RegisterNodeRequest::mutable_volume_ids() {
  // @@protoc_insertion_point(field_mutable_list:fs.mds.RegisterNodeRequest.volume_ids)
  return &volume_ids_;
}

// -------------------------------------------------------------------

// RegisterNodeResponse

// .fs.common.StatusCode status = 1;
inline void RegisterNodeResponse::clear_status() {
  status_ = 0;
}
inline ::fs::common::StatusCode RegisterNodeResponse::_internal_status() const {
  return static_cast< ::fs::common::StatusCode >(status_);
}
inline ::fs::common::StatusCode RegisterNodeResponse::status() const {
  // @@protoc_insertion_point(field_get:fs.mds.RegisterNodeResponse.status)
  return _internal_status();
}
inline void RegisterNodeResponse::_internal_set_status(::fs::common::StatusCode value) {
  
  status_ = value;
}
inline void RegisterNodeResponse::set_status(::fs::common::StatusCode value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:fs.mds.RegisterNodeResponse.status)
}

// -------------------------------------------------------------------

// CreateFileRequest

// string path = 1;
inline void CreateFileRequest::clear_path() {
  path_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& CreateFileRequest::path() const {
  // @@protoc_insertion_point(field_get:fs.mds.CreateFileRequest.path)
  return _internal_path();
}
inline void CreateFileRequest::set_path(const std::string& value) {
  _internal_set_path(value);
  // @@protoc_insertion_point(field_set:fs.mds.CreateFileRequest.path)
}
inline std::string* CreateFileRequest::mutable_path() {
  // @@protoc_insertion_point(field_mutable:fs.mds.CreateFileRequest.path)
  return _internal_mutable_path();
}
inline const std::string& CreateFileRequest::_internal_path() const {
  return path_.Get();
}
inline void CreateFileRequest::_internal_set_path(const std::string& value) {
  
  path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void CreateFileRequest::set_path(std::string&& value) {
  
  path_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:fs.mds.CreateFileRequest.path)
}
inline void CreateFileRequest::set_path(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:fs.mds.CreateFileRequest.path)
}
inline void CreateFileRequest::set_path(const char* value,
    size_t size) {
  
  path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:fs.mds.CreateFileRequest.path)
}
inline std::string* CreateFileRequest::_internal_mutable_path() {
  
  return path_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* CreateFileRequest::release_path() {
  // @@protoc_insertion_point(field_release:fs.mds.CreateFileRequest.path)
  return path_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CreateFileRequest::set_allocated_path(std::string* path) {
  if (path != nullptr) {
    
  } else {
    
  }
  path_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), path,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:fs.mds.CreateFileRequest.path)
}
inline std::string* CreateFileRequest::unsafe_arena_release_path() {
  // @@protoc_insertion_point(field_unsafe_arena_release:fs.mds.CreateFileRequest.path)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return path_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void CreateFileRequest::unsafe_arena_set_allocated_path(
    std::string* path) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (path != nullptr) {
    
  } else {
    
  }
  path_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      path, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:fs.mds.CreateFileRequest.path)
}

// int32 mode = 2;
inline void CreateFileRequest::clear_mode() {
  mode_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CreateFileRequest::_internal_mode() const {
  return mode_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CreateFileRequest::mode() const {
  // @@protoc_insertion_point(field_get:fs.mds.CreateFileRequest.mode)
  return _internal_mode();
}
inline void CreateFileRequest::_internal_set_mode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  mode_ = value;
}
inline void CreateFileRequest::set_mode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_mode(value);
  // @@protoc_insertion_point(field_set:fs.mds.CreateFileRequest.mode)
}

// -------------------------------------------------------------------

// CreateFileResponse

// .fs.common.StatusCode status = 1;
inline void CreateFileResponse::clear_status() {
  status_ = 0;
}
inline ::fs::common::StatusCode CreateFileResponse::_internal_status() const {
  return static_cast< ::fs::common::StatusCode >(status_);
}
inline ::fs::common::StatusCode CreateFileResponse::status() const {
  // @@protoc_insertion_point(field_get:fs.mds.CreateFileResponse.status)
  return _internal_status();
}
inline void CreateFileResponse::_internal_set_status(::fs::common::StatusCode value) {
  
  status_ = value;
}
inline void CreateFileResponse::set_status(::fs::common::StatusCode value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:fs.mds.CreateFileResponse.status)
}

// uint64 inode_id = 2;
inline void CreateFileResponse::clear_inode_id() {
  inode_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CreateFileResponse::_internal_inode_id() const {
  return inode_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CreateFileResponse::inode_id() const {
  // @@protoc_insertion_point(field_get:fs.mds.CreateFileResponse.inode_id)
  return _internal_inode_id();
}
inline void CreateFileResponse::_internal_set_inode_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  inode_id_ = value;
}
inline void CreateFileResponse::set_inode_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_inode_id(value);
  // @@protoc_insertion_point(field_set:fs.mds.CreateFileResponse.inode_id)
}

// -------------------------------------------------------------------

// LookupRequest

// string path = 1;
inline void LookupRequest::clear_path() {
  path_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& LookupRequest::path() const {
  // @@protoc_insertion_point(field_get:fs.mds.LookupRequest.path)
  return _internal_path();
}
inline void LookupRequest::set_path(const std::string& value) {
  _internal_set_path(value);
  // @@protoc_insertion_point(field_set:fs.mds.LookupRequest.path)
}
inline std::string* LookupRequest::mutable_path() {
  // @@protoc_insertion_point(field_mutable:fs.mds.LookupRequest.path)
  return _internal_mutable_path();
}
inline const std::string& LookupRequest::_internal_path() const {
  return path_.Get();
}
inline void LookupRequest::_internal_set_path(const std::string& value) {
  
  path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void LookupRequest::set_path(std::string&& value) {
  
  path_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:fs.mds.LookupRequest.path)
}
inline void LookupRequest::set_path(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:fs.mds.LookupRequest.path)
}
inline void LookupRequest::set_path(const char* value,
    size_t size) {
  
  path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:fs.mds.LookupRequest.path)
}
inline std::string* LookupRequest::_internal_mutable_path() {
  
  return path_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* LookupRequest::release_path() {
  // @@protoc_insertion_point(field_release:fs.mds.LookupRequest.path)
  return path_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LookupRequest::set_allocated_path(std::string* path) {
  if (path != nullptr) {
    
  } else {
    
  }
  path_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), path,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:fs.mds.LookupRequest.path)
}
inline std::string* LookupRequest::unsafe_arena_release_path() {
  // @@protoc_insertion_point(field_unsafe_arena_release:fs.mds.LookupRequest.path)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return path_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void LookupRequest::unsafe_arena_set_allocated_path(
    std::string* path) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (path != nullptr) {
    
  } else {
    
  }
  path_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      path, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:fs.mds.LookupRequest.path)
}

// -------------------------------------------------------------------

// LookupResponse

// .fs.common.StatusCode status = 1;
inline void LookupResponse::clear_status() {
  status_ = 0;
}
inline ::fs::common::StatusCode LookupResponse::_internal_status() const {
  return static_cast< ::fs::common::StatusCode >(status_);
}
inline ::fs::common::StatusCode LookupResponse::status() const {
  // @@protoc_insertion_point(field_get:fs.mds.LookupResponse.status)
  return _internal_status();
}
inline void LookupResponse::_internal_set_status(::fs::common::StatusCode value) {
  
  status_ = value;
}
inline void LookupResponse::set_status(::fs::common::StatusCode value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:fs.mds.LookupResponse.status)
}

// uint64 inode_id = 2;
inline void LookupResponse::clear_inode_id() {
  inode_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 LookupResponse::_internal_inode_id() const {
  return inode_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 LookupResponse::inode_id() const {
  // @@protoc_insertion_point(field_get:fs.mds.LookupResponse.inode_id)
  return _internal_inode_id();
}
inline void LookupResponse::_internal_set_inode_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  inode_id_ = value;
}
inline void LookupResponse::set_inode_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_inode_id(value);
  // @@protoc_insertion_point(field_set:fs.mds.LookupResponse.inode_id)
}

// -------------------------------------------------------------------

// GetBlockInfoRequest

// uint64 inode_id = 1;
inline void GetBlockInfoRequest::clear_inode_id() {
  inode_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GetBlockInfoRequest::_internal_inode_id() const {
  return inode_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GetBlockInfoRequest::inode_id() const {
  // @@protoc_insertion_point(field_get:fs.mds.GetBlockInfoRequest.inode_id)
  return _internal_inode_id();
}
inline void GetBlockInfoRequest::_internal_set_inode_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  inode_id_ = value;
}
inline void GetBlockInfoRequest::set_inode_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_inode_id(value);
  // @@protoc_insertion_point(field_set:fs.mds.GetBlockInfoRequest.inode_id)
}

// uint64 file_offset = 2;
inline void GetBlockInfoRequest::clear_file_offset() {
  file_offset_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GetBlockInfoRequest::_internal_file_offset() const {
  return file_offset_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GetBlockInfoRequest::file_offset() const {
  // @@protoc_insertion_point(field_get:fs.mds.GetBlockInfoRequest.file_offset)
  return _internal_file_offset();
}
inline void GetBlockInfoRequest::_internal_set_file_offset(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  file_offset_ = value;
}
inline void GetBlockInfoRequest::set_file_offset(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_file_offset(value);
  // @@protoc_insertion_point(field_set:fs.mds.GetBlockInfoRequest.file_offset)
}

// bool is_write = 3;
inline void GetBlockInfoRequest::clear_is_write() {
  is_write_ = false;
}
inline bool GetBlockInfoRequest::_internal_is_write() const {
  return is_write_;
}
inline bool GetBlockInfoRequest::is_write() const {
  // @@protoc_insertion_point(field_get:fs.mds.GetBlockInfoRequest.is_write)
  return _internal_is_write();
}
inline void GetBlockInfoRequest::_internal_set_is_write(bool value) {
  
  is_write_ = value;
}
inline void GetBlockInfoRequest::set_is_write(bool value) {
  _internal_set_is_write(value);
  // @@protoc_insertion_point(field_set:fs.mds.GetBlockInfoRequest.is_write)
}

// -------------------------------------------------------------------

// GetBlockInfoResponse

// .fs.common.StatusCode status = 1;
inline void GetBlockInfoResponse::clear_status() {
  status_ = 0;
}
inline ::fs::common::StatusCode GetBlockInfoResponse::_internal_status() const {
  return static_cast< ::fs::common::StatusCode >(status_);
}
inline ::fs::common::StatusCode GetBlockInfoResponse::status() const {
  // @@protoc_insertion_point(field_get:fs.mds.GetBlockInfoResponse.status)
  return _internal_status();
}
inline void GetBlockInfoResponse::_internal_set_status(::fs::common::StatusCode value) {
  
  status_ = value;
}
inline void GetBlockInfoResponse::set_status(::fs::common::StatusCode value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:fs.mds.GetBlockInfoResponse.status)
}

// string storage_addr = 2;
inline void GetBlockInfoResponse::clear_storage_addr() {
  storage_addr_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& GetBlockInfoResponse::storage_addr() const {
  // @@protoc_insertion_point(field_get:fs.mds.GetBlockInfoResponse.storage_addr)
  return _internal_storage_addr();
}
inline void GetBlockInfoResponse::set_storage_addr(const std::string& value) {
  _internal_set_storage_addr(value);
  // @@protoc_insertion_point(field_set:fs.mds.GetBlockInfoResponse.storage_addr)
}
inline std::string* GetBlockInfoResponse::mutable_storage_addr() {
  // @@protoc_insertion_point(field_mutable:fs.mds.GetBlockInfoResponse.storage_addr)
  return _internal_mutable_storage_addr();
}
inline const std::string& GetBlockInfoResponse::_internal_storage_addr() const {
  return storage_addr_.Get();
}
inline void GetBlockInfoResponse::_internal_set_storage_addr(const std::string& value) {
  
  storage_addr_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void GetBlockInfoResponse::set_storage_addr(std::string&& value) {
  
  storage_addr_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:fs.mds.GetBlockInfoResponse.storage_addr)
}
inline void GetBlockInfoResponse::set_storage_addr(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  storage_addr_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:fs.mds.GetBlockInfoResponse.storage_addr)
}
inline void GetBlockInfoResponse::set_storage_addr(const char* value,
    size_t size) {
  
  storage_addr_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:fs.mds.GetBlockInfoResponse.storage_addr)
}
inline std::string* GetBlockInfoResponse::_internal_mutable_storage_addr() {
  
  return storage_addr_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* GetBlockInfoResponse::release_storage_addr() {
  // @@protoc_insertion_point(field_release:fs.mds.GetBlockInfoResponse.storage_addr)
  return storage_addr_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GetBlockInfoResponse::set_allocated_storage_addr(std::string* storage_addr) {
  if (storage_addr != nullptr) {
    
  } else {
    
  }
  storage_addr_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), storage_addr,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:fs.mds.GetBlockInfoResponse.storage_addr)
}
inline std::string* GetBlockInfoResponse::unsafe_arena_release_storage_addr() {
  // @@protoc_insertion_point(field_unsafe_arena_release:fs.mds.GetBlockInfoResponse.storage_addr)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return storage_addr_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void GetBlockInfoResponse::unsafe_arena_set_allocated_storage_addr(
    std::string* storage_addr) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (storage_addr != nullptr) {
    
  } else {
    
  }
  storage_addr_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      storage_addr, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:fs.mds.GetBlockInfoResponse.storage_addr)
}

// uint64 volume_id = 3;
inline void GetBlockInfoResponse::clear_volume_id() {
  volume_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GetBlockInfoResponse::_internal_volume_id() const {
  return volume_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GetBlockInfoResponse::volume_id() const {
  // @@protoc_insertion_point(field_get:fs.mds.GetBlockInfoResponse.volume_id)
  return _internal_volume_id();
}
inline void GetBlockInfoResponse::_internal_set_volume_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  volume_id_ = value;
}
inline void GetBlockInfoResponse::set_volume_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_volume_id(value);
  // @@protoc_insertion_point(field_set:fs.mds.GetBlockInfoResponse.volume_id)
}

// uint64 block_offset = 4;
inline void GetBlockInfoResponse::clear_block_offset() {
  block_offset_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GetBlockInfoResponse::_internal_block_offset() const {
  return block_offset_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GetBlockInfoResponse::block_offset() const {
  // @@protoc_insertion_point(field_get:fs.mds.GetBlockInfoResponse.block_offset)
  return _internal_block_offset();
}
inline void GetBlockInfoResponse::_internal_set_block_offset(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  block_offset_ = value;
}
inline void GetBlockInfoResponse::set_block_offset(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_block_offset(value);
  // @@protoc_insertion_point(field_set:fs.mds.GetBlockInfoResponse.block_offset)
}

// uint64 block_length = 5;
inline void GetBlockInfoResponse::clear_block_length() {
  block_length_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GetBlockInfoResponse::_internal_block_length() const {
  return block_length_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GetBlockInfoResponse::block_length() const {
  // @@protoc_insertion_point(field_get:fs.mds.GetBlockInfoResponse.block_length)
  return _internal_block_length();
}
inline void GetBlockInfoResponse::_internal_set_block_length(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  block_length_ = value;
}
inline void GetBlockInfoResponse::set_block_length(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_block_length(value);
  // @@protoc_insertion_point(field_set:fs.mds.GetBlockInfoResponse.block_length)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mds
}  // namespace fs

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_mds_2eproto
