// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mds.proto

#include "mds.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace fs {
namespace mds {
class RegisterNodeRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RegisterNodeRequest> _instance;
} _RegisterNodeRequest_default_instance_;
class RegisterNodeResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RegisterNodeResponse> _instance;
} _RegisterNodeResponse_default_instance_;
class CreateFileRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<CreateFileRequest> _instance;
} _CreateFileRequest_default_instance_;
class CreateFileResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<CreateFileResponse> _instance;
} _CreateFileResponse_default_instance_;
class LookupRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<LookupRequest> _instance;
} _LookupRequest_default_instance_;
class LookupResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<LookupResponse> _instance;
} _LookupResponse_default_instance_;
class GetBlockInfoRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GetBlockInfoRequest> _instance;
} _GetBlockInfoRequest_default_instance_;
class GetBlockInfoResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GetBlockInfoResponse> _instance;
} _GetBlockInfoResponse_default_instance_;
}  // namespace mds
}  // namespace fs
static void InitDefaultsscc_info_CreateFileRequest_mds_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::fs::mds::_CreateFileRequest_default_instance_;
    new (ptr) ::fs::mds::CreateFileRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::fs::mds::CreateFileRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CreateFileRequest_mds_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_CreateFileRequest_mds_2eproto}, {}};

static void InitDefaultsscc_info_CreateFileResponse_mds_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::fs::mds::_CreateFileResponse_default_instance_;
    new (ptr) ::fs::mds::CreateFileResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::fs::mds::CreateFileResponse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CreateFileResponse_mds_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_CreateFileResponse_mds_2eproto}, {}};

static void InitDefaultsscc_info_GetBlockInfoRequest_mds_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::fs::mds::_GetBlockInfoRequest_default_instance_;
    new (ptr) ::fs::mds::GetBlockInfoRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::fs::mds::GetBlockInfoRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GetBlockInfoRequest_mds_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GetBlockInfoRequest_mds_2eproto}, {}};

static void InitDefaultsscc_info_GetBlockInfoResponse_mds_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::fs::mds::_GetBlockInfoResponse_default_instance_;
    new (ptr) ::fs::mds::GetBlockInfoResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::fs::mds::GetBlockInfoResponse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GetBlockInfoResponse_mds_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GetBlockInfoResponse_mds_2eproto}, {}};

static void InitDefaultsscc_info_LookupRequest_mds_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::fs::mds::_LookupRequest_default_instance_;
    new (ptr) ::fs::mds::LookupRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::fs::mds::LookupRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_LookupRequest_mds_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_LookupRequest_mds_2eproto}, {}};

static void InitDefaultsscc_info_LookupResponse_mds_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::fs::mds::_LookupResponse_default_instance_;
    new (ptr) ::fs::mds::LookupResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::fs::mds::LookupResponse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_LookupResponse_mds_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_LookupResponse_mds_2eproto}, {}};

static void InitDefaultsscc_info_RegisterNodeRequest_mds_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::fs::mds::_RegisterNodeRequest_default_instance_;
    new (ptr) ::fs::mds::RegisterNodeRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::fs::mds::RegisterNodeRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RegisterNodeRequest_mds_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_RegisterNodeRequest_mds_2eproto}, {}};

static void InitDefaultsscc_info_RegisterNodeResponse_mds_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::fs::mds::_RegisterNodeResponse_default_instance_;
    new (ptr) ::fs::mds::RegisterNodeResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::fs::mds::RegisterNodeResponse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RegisterNodeResponse_mds_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_RegisterNodeResponse_mds_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_mds_2eproto[8];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_mds_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* file_level_service_descriptors_mds_2eproto[1];

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_mds_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fs::mds::RegisterNodeRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::fs::mds::RegisterNodeRequest, address_),
  PROTOBUF_FIELD_OFFSET(::fs::mds::RegisterNodeRequest, volume_ids_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fs::mds::RegisterNodeResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::fs::mds::RegisterNodeResponse, status_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fs::mds::CreateFileRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::fs::mds::CreateFileRequest, path_),
  PROTOBUF_FIELD_OFFSET(::fs::mds::CreateFileRequest, mode_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fs::mds::CreateFileResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::fs::mds::CreateFileResponse, status_),
  PROTOBUF_FIELD_OFFSET(::fs::mds::CreateFileResponse, inode_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fs::mds::LookupRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::fs::mds::LookupRequest, path_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fs::mds::LookupResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::fs::mds::LookupResponse, status_),
  PROTOBUF_FIELD_OFFSET(::fs::mds::LookupResponse, inode_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fs::mds::GetBlockInfoRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::fs::mds::GetBlockInfoRequest, inode_id_),
  PROTOBUF_FIELD_OFFSET(::fs::mds::GetBlockInfoRequest, file_offset_),
  PROTOBUF_FIELD_OFFSET(::fs::mds::GetBlockInfoRequest, is_write_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fs::mds::GetBlockInfoResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::fs::mds::GetBlockInfoResponse, status_),
  PROTOBUF_FIELD_OFFSET(::fs::mds::GetBlockInfoResponse, storage_addr_),
  PROTOBUF_FIELD_OFFSET(::fs::mds::GetBlockInfoResponse, volume_id_),
  PROTOBUF_FIELD_OFFSET(::fs::mds::GetBlockInfoResponse, block_offset_),
  PROTOBUF_FIELD_OFFSET(::fs::mds::GetBlockInfoResponse, block_length_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::fs::mds::RegisterNodeRequest)},
  { 7, -1, sizeof(::fs::mds::RegisterNodeResponse)},
  { 13, -1, sizeof(::fs::mds::CreateFileRequest)},
  { 20, -1, sizeof(::fs::mds::CreateFileResponse)},
  { 27, -1, sizeof(::fs::mds::LookupRequest)},
  { 33, -1, sizeof(::fs::mds::LookupResponse)},
  { 40, -1, sizeof(::fs::mds::GetBlockInfoRequest)},
  { 48, -1, sizeof(::fs::mds::GetBlockInfoResponse)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::fs::mds::_RegisterNodeRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::fs::mds::_RegisterNodeResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::fs::mds::_CreateFileRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::fs::mds::_CreateFileResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::fs::mds::_LookupRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::fs::mds::_LookupResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::fs::mds::_GetBlockInfoRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::fs::mds::_GetBlockInfoResponse_default_instance_),
};

const char descriptor_table_protodef_mds_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\tmds.proto\022\006fs.mds\032\014common.proto\":\n\023Reg"
  "isterNodeRequest\022\017\n\007address\030\001 \001(\t\022\022\n\nvol"
  "ume_ids\030\002 \003(\t\"=\n\024RegisterNodeResponse\022%\n"
  "\006status\030\001 \001(\0162\025.fs.common.StatusCode\"/\n\021"
  "CreateFileRequest\022\014\n\004path\030\001 \001(\t\022\014\n\004mode\030"
  "\002 \001(\005\"M\n\022CreateFileResponse\022%\n\006status\030\001 "
  "\001(\0162\025.fs.common.StatusCode\022\020\n\010inode_id\030\002"
  " \001(\004\"\035\n\rLookupRequest\022\014\n\004path\030\001 \001(\t\"I\n\016L"
  "ookupResponse\022%\n\006status\030\001 \001(\0162\025.fs.commo"
  "n.StatusCode\022\020\n\010inode_id\030\002 \001(\004\"N\n\023GetBlo"
  "ckInfoRequest\022\020\n\010inode_id\030\001 \001(\004\022\023\n\013file_"
  "offset\030\002 \001(\004\022\020\n\010is_write\030\003 \001(\010\"\222\001\n\024GetBl"
  "ockInfoResponse\022%\n\006status\030\001 \001(\0162\025.fs.com"
  "mon.StatusCode\022\024\n\014storage_addr\030\002 \001(\t\022\021\n\t"
  "volume_id\030\003 \001(\004\022\024\n\014block_offset\030\004 \001(\004\022\024\n"
  "\014block_length\030\005 \001(\0042\240\002\n\nMdsService\022I\n\014Re"
  "gisterNode\022\033.fs.mds.RegisterNodeRequest\032"
  "\034.fs.mds.RegisterNodeResponse\022C\n\nCreateF"
  "ile\022\031.fs.mds.CreateFileRequest\032\032.fs.mds."
  "CreateFileResponse\0227\n\006Lookup\022\025.fs.mds.Lo"
  "okupRequest\032\026.fs.mds.LookupResponse\022I\n\014G"
  "etBlockInfo\022\033.fs.mds.GetBlockInfoRequest"
  "\032\034.fs.mds.GetBlockInfoResponseB\003\200\001\001b\006pro"
  "to3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_mds_2eproto_deps[1] = {
  &::descriptor_table_common_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_mds_2eproto_sccs[8] = {
  &scc_info_CreateFileRequest_mds_2eproto.base,
  &scc_info_CreateFileResponse_mds_2eproto.base,
  &scc_info_GetBlockInfoRequest_mds_2eproto.base,
  &scc_info_GetBlockInfoResponse_mds_2eproto.base,
  &scc_info_LookupRequest_mds_2eproto.base,
  &scc_info_LookupResponse_mds_2eproto.base,
  &scc_info_RegisterNodeRequest_mds_2eproto.base,
  &scc_info_RegisterNodeResponse_mds_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_mds_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mds_2eproto = {
  false, false, descriptor_table_protodef_mds_2eproto, "mds.proto", 923,
  &descriptor_table_mds_2eproto_once, descriptor_table_mds_2eproto_sccs, descriptor_table_mds_2eproto_deps, 8, 1,
  schemas, file_default_instances, TableStruct_mds_2eproto::offsets,
  file_level_metadata_mds_2eproto, 8, file_level_enum_descriptors_mds_2eproto, file_level_service_descriptors_mds_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_mds_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_mds_2eproto)), true);
namespace fs {
namespace mds {

// ===================================================================

void RegisterNodeRequest::InitAsDefaultInstance() {
}
class RegisterNodeRequest::_Internal {
 public:
};

RegisterNodeRequest::RegisterNodeRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  volume_ids_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:fs.mds.RegisterNodeRequest)
}
RegisterNodeRequest::RegisterNodeRequest(const RegisterNodeRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      volume_ids_(from.volume_ids_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  address_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_address().empty()) {
    address_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_address(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:fs.mds.RegisterNodeRequest)
}

void RegisterNodeRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_RegisterNodeRequest_mds_2eproto.base);
  address_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

RegisterNodeRequest::~RegisterNodeRequest() {
  // @@protoc_insertion_point(destructor:fs.mds.RegisterNodeRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RegisterNodeRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  address_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void RegisterNodeRequest::ArenaDtor(void* object) {
  RegisterNodeRequest* _this = reinterpret_cast< RegisterNodeRequest* >(object);
  (void)_this;
}
void RegisterNodeRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RegisterNodeRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RegisterNodeRequest& RegisterNodeRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RegisterNodeRequest_mds_2eproto.base);
  return *internal_default_instance();
}


void RegisterNodeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:fs.mds.RegisterNodeRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  volume_ids_.Clear();
  address_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RegisterNodeRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string address = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_address();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "fs.mds.RegisterNodeRequest.address"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated string volume_ids = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_volume_ids();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "fs.mds.RegisterNodeRequest.volume_ids"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RegisterNodeRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fs.mds.RegisterNodeRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string address = 1;
  if (this->address().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_address().data(), static_cast<int>(this->_internal_address().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "fs.mds.RegisterNodeRequest.address");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_address(), target);
  }

  // repeated string volume_ids = 2;
  for (int i = 0, n = this->_internal_volume_ids_size(); i < n; i++) {
    const auto& s = this->_internal_volume_ids(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "fs.mds.RegisterNodeRequest.volume_ids");
    target = stream->WriteString(2, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fs.mds.RegisterNodeRequest)
  return target;
}

size_t RegisterNodeRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fs.mds.RegisterNodeRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string volume_ids = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(volume_ids_.size());
  for (int i = 0, n = volume_ids_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      volume_ids_.Get(i));
  }

  // string address = 1;
  if (this->address().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_address());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RegisterNodeRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:fs.mds.RegisterNodeRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const RegisterNodeRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RegisterNodeRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:fs.mds.RegisterNodeRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:fs.mds.RegisterNodeRequest)
    MergeFrom(*source);
  }
}

void RegisterNodeRequest::MergeFrom(const RegisterNodeRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fs.mds.RegisterNodeRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  volume_ids_.MergeFrom(from.volume_ids_);
  if (from.address().size() > 0) {
    _internal_set_address(from._internal_address());
  }
}

void RegisterNodeRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:fs.mds.RegisterNodeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RegisterNodeRequest::CopyFrom(const RegisterNodeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fs.mds.RegisterNodeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RegisterNodeRequest::IsInitialized() const {
  return true;
}

void RegisterNodeRequest::InternalSwap(RegisterNodeRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  volume_ids_.InternalSwap(&other->volume_ids_);
  address_.Swap(&other->address_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata RegisterNodeRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void RegisterNodeResponse::InitAsDefaultInstance() {
}
class RegisterNodeResponse::_Internal {
 public:
};

RegisterNodeResponse::RegisterNodeResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:fs.mds.RegisterNodeResponse)
}
RegisterNodeResponse::RegisterNodeResponse(const RegisterNodeResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  status_ = from.status_;
  // @@protoc_insertion_point(copy_constructor:fs.mds.RegisterNodeResponse)
}

void RegisterNodeResponse::SharedCtor() {
  status_ = 0;
}

RegisterNodeResponse::~RegisterNodeResponse() {
  // @@protoc_insertion_point(destructor:fs.mds.RegisterNodeResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RegisterNodeResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void RegisterNodeResponse::ArenaDtor(void* object) {
  RegisterNodeResponse* _this = reinterpret_cast< RegisterNodeResponse* >(object);
  (void)_this;
}
void RegisterNodeResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RegisterNodeResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RegisterNodeResponse& RegisterNodeResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RegisterNodeResponse_mds_2eproto.base);
  return *internal_default_instance();
}


void RegisterNodeResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:fs.mds.RegisterNodeResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  status_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RegisterNodeResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .fs.common.StatusCode status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_status(static_cast<::fs::common::StatusCode>(val));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RegisterNodeResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fs.mds.RegisterNodeResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .fs.common.StatusCode status = 1;
  if (this->status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_status(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fs.mds.RegisterNodeResponse)
  return target;
}

size_t RegisterNodeResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fs.mds.RegisterNodeResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .fs.common.StatusCode status = 1;
  if (this->status() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_status());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RegisterNodeResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:fs.mds.RegisterNodeResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const RegisterNodeResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RegisterNodeResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:fs.mds.RegisterNodeResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:fs.mds.RegisterNodeResponse)
    MergeFrom(*source);
  }
}

void RegisterNodeResponse::MergeFrom(const RegisterNodeResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fs.mds.RegisterNodeResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.status() != 0) {
    _internal_set_status(from._internal_status());
  }
}

void RegisterNodeResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:fs.mds.RegisterNodeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RegisterNodeResponse::CopyFrom(const RegisterNodeResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fs.mds.RegisterNodeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RegisterNodeResponse::IsInitialized() const {
  return true;
}

void RegisterNodeResponse::InternalSwap(RegisterNodeResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(status_, other->status_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RegisterNodeResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void CreateFileRequest::InitAsDefaultInstance() {
}
class CreateFileRequest::_Internal {
 public:
};

CreateFileRequest::CreateFileRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:fs.mds.CreateFileRequest)
}
CreateFileRequest::CreateFileRequest(const CreateFileRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  path_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_path().empty()) {
    path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_path(),
      GetArena());
  }
  mode_ = from.mode_;
  // @@protoc_insertion_point(copy_constructor:fs.mds.CreateFileRequest)
}

void CreateFileRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_CreateFileRequest_mds_2eproto.base);
  path_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  mode_ = 0;
}

CreateFileRequest::~CreateFileRequest() {
  // @@protoc_insertion_point(destructor:fs.mds.CreateFileRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void CreateFileRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  path_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void CreateFileRequest::ArenaDtor(void* object) {
  CreateFileRequest* _this = reinterpret_cast< CreateFileRequest* >(object);
  (void)_this;
}
void CreateFileRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void CreateFileRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CreateFileRequest& CreateFileRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_CreateFileRequest_mds_2eproto.base);
  return *internal_default_instance();
}


void CreateFileRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:fs.mds.CreateFileRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  path_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  mode_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CreateFileRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string path = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_path();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "fs.mds.CreateFileRequest.path"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 mode = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          mode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CreateFileRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fs.mds.CreateFileRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string path = 1;
  if (this->path().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_path().data(), static_cast<int>(this->_internal_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "fs.mds.CreateFileRequest.path");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_path(), target);
  }

  // int32 mode = 2;
  if (this->mode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_mode(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fs.mds.CreateFileRequest)
  return target;
}

size_t CreateFileRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fs.mds.CreateFileRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string path = 1;
  if (this->path().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_path());
  }

  // int32 mode = 2;
  if (this->mode() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_mode());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CreateFileRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:fs.mds.CreateFileRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const CreateFileRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CreateFileRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:fs.mds.CreateFileRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:fs.mds.CreateFileRequest)
    MergeFrom(*source);
  }
}

void CreateFileRequest::MergeFrom(const CreateFileRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fs.mds.CreateFileRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.path().size() > 0) {
    _internal_set_path(from._internal_path());
  }
  if (from.mode() != 0) {
    _internal_set_mode(from._internal_mode());
  }
}

void CreateFileRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:fs.mds.CreateFileRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CreateFileRequest::CopyFrom(const CreateFileRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fs.mds.CreateFileRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CreateFileRequest::IsInitialized() const {
  return true;
}

void CreateFileRequest::InternalSwap(CreateFileRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  path_.Swap(&other->path_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(mode_, other->mode_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CreateFileRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void CreateFileResponse::InitAsDefaultInstance() {
}
class CreateFileResponse::_Internal {
 public:
};

CreateFileResponse::CreateFileResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:fs.mds.CreateFileResponse)
}
CreateFileResponse::CreateFileResponse(const CreateFileResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&inode_id_, &from.inode_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&status_) -
    reinterpret_cast<char*>(&inode_id_)) + sizeof(status_));
  // @@protoc_insertion_point(copy_constructor:fs.mds.CreateFileResponse)
}

void CreateFileResponse::SharedCtor() {
  ::memset(&inode_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&status_) -
      reinterpret_cast<char*>(&inode_id_)) + sizeof(status_));
}

CreateFileResponse::~CreateFileResponse() {
  // @@protoc_insertion_point(destructor:fs.mds.CreateFileResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void CreateFileResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void CreateFileResponse::ArenaDtor(void* object) {
  CreateFileResponse* _this = reinterpret_cast< CreateFileResponse* >(object);
  (void)_this;
}
void CreateFileResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void CreateFileResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CreateFileResponse& CreateFileResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_CreateFileResponse_mds_2eproto.base);
  return *internal_default_instance();
}


void CreateFileResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:fs.mds.CreateFileResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&inode_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&status_) -
      reinterpret_cast<char*>(&inode_id_)) + sizeof(status_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CreateFileResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .fs.common.StatusCode status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_status(static_cast<::fs::common::StatusCode>(val));
        } else goto handle_unusual;
        continue;
      // uint64 inode_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          inode_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CreateFileResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fs.mds.CreateFileResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .fs.common.StatusCode status = 1;
  if (this->status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_status(), target);
  }

  // uint64 inode_id = 2;
  if (this->inode_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(2, this->_internal_inode_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fs.mds.CreateFileResponse)
  return target;
}

size_t CreateFileResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fs.mds.CreateFileResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 inode_id = 2;
  if (this->inode_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_inode_id());
  }

  // .fs.common.StatusCode status = 1;
  if (this->status() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_status());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CreateFileResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:fs.mds.CreateFileResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const CreateFileResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CreateFileResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:fs.mds.CreateFileResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:fs.mds.CreateFileResponse)
    MergeFrom(*source);
  }
}

void CreateFileResponse::MergeFrom(const CreateFileResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fs.mds.CreateFileResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.inode_id() != 0) {
    _internal_set_inode_id(from._internal_inode_id());
  }
  if (from.status() != 0) {
    _internal_set_status(from._internal_status());
  }
}

void CreateFileResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:fs.mds.CreateFileResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CreateFileResponse::CopyFrom(const CreateFileResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fs.mds.CreateFileResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CreateFileResponse::IsInitialized() const {
  return true;
}

void CreateFileResponse::InternalSwap(CreateFileResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CreateFileResponse, status_)
      + sizeof(CreateFileResponse::status_)
      - PROTOBUF_FIELD_OFFSET(CreateFileResponse, inode_id_)>(
          reinterpret_cast<char*>(&inode_id_),
          reinterpret_cast<char*>(&other->inode_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CreateFileResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void LookupRequest::InitAsDefaultInstance() {
}
class LookupRequest::_Internal {
 public:
};

LookupRequest::LookupRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:fs.mds.LookupRequest)
}
LookupRequest::LookupRequest(const LookupRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  path_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_path().empty()) {
    path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_path(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:fs.mds.LookupRequest)
}

void LookupRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_LookupRequest_mds_2eproto.base);
  path_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

LookupRequest::~LookupRequest() {
  // @@protoc_insertion_point(destructor:fs.mds.LookupRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void LookupRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  path_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void LookupRequest::ArenaDtor(void* object) {
  LookupRequest* _this = reinterpret_cast< LookupRequest* >(object);
  (void)_this;
}
void LookupRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void LookupRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const LookupRequest& LookupRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_LookupRequest_mds_2eproto.base);
  return *internal_default_instance();
}


void LookupRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:fs.mds.LookupRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  path_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LookupRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string path = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_path();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "fs.mds.LookupRequest.path"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* LookupRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fs.mds.LookupRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string path = 1;
  if (this->path().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_path().data(), static_cast<int>(this->_internal_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "fs.mds.LookupRequest.path");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_path(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fs.mds.LookupRequest)
  return target;
}

size_t LookupRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fs.mds.LookupRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string path = 1;
  if (this->path().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_path());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LookupRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:fs.mds.LookupRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const LookupRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<LookupRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:fs.mds.LookupRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:fs.mds.LookupRequest)
    MergeFrom(*source);
  }
}

void LookupRequest::MergeFrom(const LookupRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fs.mds.LookupRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.path().size() > 0) {
    _internal_set_path(from._internal_path());
  }
}

void LookupRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:fs.mds.LookupRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LookupRequest::CopyFrom(const LookupRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fs.mds.LookupRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LookupRequest::IsInitialized() const {
  return true;
}

void LookupRequest::InternalSwap(LookupRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  path_.Swap(&other->path_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata LookupRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void LookupResponse::InitAsDefaultInstance() {
}
class LookupResponse::_Internal {
 public:
};

LookupResponse::LookupResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:fs.mds.LookupResponse)
}
LookupResponse::LookupResponse(const LookupResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&inode_id_, &from.inode_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&status_) -
    reinterpret_cast<char*>(&inode_id_)) + sizeof(status_));
  // @@protoc_insertion_point(copy_constructor:fs.mds.LookupResponse)
}

void LookupResponse::SharedCtor() {
  ::memset(&inode_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&status_) -
      reinterpret_cast<char*>(&inode_id_)) + sizeof(status_));
}

LookupResponse::~LookupResponse() {
  // @@protoc_insertion_point(destructor:fs.mds.LookupResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void LookupResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void LookupResponse::ArenaDtor(void* object) {
  LookupResponse* _this = reinterpret_cast< LookupResponse* >(object);
  (void)_this;
}
void LookupResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void LookupResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const LookupResponse& LookupResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_LookupResponse_mds_2eproto.base);
  return *internal_default_instance();
}


void LookupResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:fs.mds.LookupResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&inode_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&status_) -
      reinterpret_cast<char*>(&inode_id_)) + sizeof(status_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LookupResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .fs.common.StatusCode status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_status(static_cast<::fs::common::StatusCode>(val));
        } else goto handle_unusual;
        continue;
      // uint64 inode_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          inode_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* LookupResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fs.mds.LookupResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .fs.common.StatusCode status = 1;
  if (this->status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_status(), target);
  }

  // uint64 inode_id = 2;
  if (this->inode_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(2, this->_internal_inode_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fs.mds.LookupResponse)
  return target;
}

size_t LookupResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fs.mds.LookupResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 inode_id = 2;
  if (this->inode_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_inode_id());
  }

  // .fs.common.StatusCode status = 1;
  if (this->status() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_status());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LookupResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:fs.mds.LookupResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const LookupResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<LookupResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:fs.mds.LookupResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:fs.mds.LookupResponse)
    MergeFrom(*source);
  }
}

void LookupResponse::MergeFrom(const LookupResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fs.mds.LookupResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.inode_id() != 0) {
    _internal_set_inode_id(from._internal_inode_id());
  }
  if (from.status() != 0) {
    _internal_set_status(from._internal_status());
  }
}

void LookupResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:fs.mds.LookupResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LookupResponse::CopyFrom(const LookupResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fs.mds.LookupResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LookupResponse::IsInitialized() const {
  return true;
}

void LookupResponse::InternalSwap(LookupResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LookupResponse, status_)
      + sizeof(LookupResponse::status_)
      - PROTOBUF_FIELD_OFFSET(LookupResponse, inode_id_)>(
          reinterpret_cast<char*>(&inode_id_),
          reinterpret_cast<char*>(&other->inode_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata LookupResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void GetBlockInfoRequest::InitAsDefaultInstance() {
}
class GetBlockInfoRequest::_Internal {
 public:
};

GetBlockInfoRequest::GetBlockInfoRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:fs.mds.GetBlockInfoRequest)
}
GetBlockInfoRequest::GetBlockInfoRequest(const GetBlockInfoRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&inode_id_, &from.inode_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&is_write_) -
    reinterpret_cast<char*>(&inode_id_)) + sizeof(is_write_));
  // @@protoc_insertion_point(copy_constructor:fs.mds.GetBlockInfoRequest)
}

void GetBlockInfoRequest::SharedCtor() {
  ::memset(&inode_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&is_write_) -
      reinterpret_cast<char*>(&inode_id_)) + sizeof(is_write_));
}

GetBlockInfoRequest::~GetBlockInfoRequest() {
  // @@protoc_insertion_point(destructor:fs.mds.GetBlockInfoRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GetBlockInfoRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void GetBlockInfoRequest::ArenaDtor(void* object) {
  GetBlockInfoRequest* _this = reinterpret_cast< GetBlockInfoRequest* >(object);
  (void)_this;
}
void GetBlockInfoRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GetBlockInfoRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GetBlockInfoRequest& GetBlockInfoRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GetBlockInfoRequest_mds_2eproto.base);
  return *internal_default_instance();
}


void GetBlockInfoRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:fs.mds.GetBlockInfoRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&inode_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&is_write_) -
      reinterpret_cast<char*>(&inode_id_)) + sizeof(is_write_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetBlockInfoRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint64 inode_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          inode_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 file_offset = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          file_offset_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool is_write = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          is_write_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GetBlockInfoRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fs.mds.GetBlockInfoRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 inode_id = 1;
  if (this->inode_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_inode_id(), target);
  }

  // uint64 file_offset = 2;
  if (this->file_offset() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(2, this->_internal_file_offset(), target);
  }

  // bool is_write = 3;
  if (this->is_write() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_is_write(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fs.mds.GetBlockInfoRequest)
  return target;
}

size_t GetBlockInfoRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fs.mds.GetBlockInfoRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 inode_id = 1;
  if (this->inode_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_inode_id());
  }

  // uint64 file_offset = 2;
  if (this->file_offset() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_file_offset());
  }

  // bool is_write = 3;
  if (this->is_write() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetBlockInfoRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:fs.mds.GetBlockInfoRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const GetBlockInfoRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GetBlockInfoRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:fs.mds.GetBlockInfoRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:fs.mds.GetBlockInfoRequest)
    MergeFrom(*source);
  }
}

void GetBlockInfoRequest::MergeFrom(const GetBlockInfoRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fs.mds.GetBlockInfoRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.inode_id() != 0) {
    _internal_set_inode_id(from._internal_inode_id());
  }
  if (from.file_offset() != 0) {
    _internal_set_file_offset(from._internal_file_offset());
  }
  if (from.is_write() != 0) {
    _internal_set_is_write(from._internal_is_write());
  }
}

void GetBlockInfoRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:fs.mds.GetBlockInfoRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetBlockInfoRequest::CopyFrom(const GetBlockInfoRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fs.mds.GetBlockInfoRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetBlockInfoRequest::IsInitialized() const {
  return true;
}

void GetBlockInfoRequest::InternalSwap(GetBlockInfoRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetBlockInfoRequest, is_write_)
      + sizeof(GetBlockInfoRequest::is_write_)
      - PROTOBUF_FIELD_OFFSET(GetBlockInfoRequest, inode_id_)>(
          reinterpret_cast<char*>(&inode_id_),
          reinterpret_cast<char*>(&other->inode_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GetBlockInfoRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void GetBlockInfoResponse::InitAsDefaultInstance() {
}
class GetBlockInfoResponse::_Internal {
 public:
};

GetBlockInfoResponse::GetBlockInfoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:fs.mds.GetBlockInfoResponse)
}
GetBlockInfoResponse::GetBlockInfoResponse(const GetBlockInfoResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  storage_addr_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_storage_addr().empty()) {
    storage_addr_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_storage_addr(),
      GetArena());
  }
  ::memcpy(&volume_id_, &from.volume_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&status_) -
    reinterpret_cast<char*>(&volume_id_)) + sizeof(status_));
  // @@protoc_insertion_point(copy_constructor:fs.mds.GetBlockInfoResponse)
}

void GetBlockInfoResponse::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_GetBlockInfoResponse_mds_2eproto.base);
  storage_addr_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&volume_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&status_) -
      reinterpret_cast<char*>(&volume_id_)) + sizeof(status_));
}

GetBlockInfoResponse::~GetBlockInfoResponse() {
  // @@protoc_insertion_point(destructor:fs.mds.GetBlockInfoResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GetBlockInfoResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  storage_addr_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void GetBlockInfoResponse::ArenaDtor(void* object) {
  GetBlockInfoResponse* _this = reinterpret_cast< GetBlockInfoResponse* >(object);
  (void)_this;
}
void GetBlockInfoResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GetBlockInfoResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GetBlockInfoResponse& GetBlockInfoResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GetBlockInfoResponse_mds_2eproto.base);
  return *internal_default_instance();
}


void GetBlockInfoResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:fs.mds.GetBlockInfoResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  storage_addr_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&volume_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&status_) -
      reinterpret_cast<char*>(&volume_id_)) + sizeof(status_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetBlockInfoResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .fs.common.StatusCode status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_status(static_cast<::fs::common::StatusCode>(val));
        } else goto handle_unusual;
        continue;
      // string storage_addr = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_storage_addr();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "fs.mds.GetBlockInfoResponse.storage_addr"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 volume_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          volume_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 block_offset = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          block_offset_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 block_length = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          block_length_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GetBlockInfoResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fs.mds.GetBlockInfoResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .fs.common.StatusCode status = 1;
  if (this->status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_status(), target);
  }

  // string storage_addr = 2;
  if (this->storage_addr().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_storage_addr().data(), static_cast<int>(this->_internal_storage_addr().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "fs.mds.GetBlockInfoResponse.storage_addr");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_storage_addr(), target);
  }

  // uint64 volume_id = 3;
  if (this->volume_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(3, this->_internal_volume_id(), target);
  }

  // uint64 block_offset = 4;
  if (this->block_offset() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(4, this->_internal_block_offset(), target);
  }

  // uint64 block_length = 5;
  if (this->block_length() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(5, this->_internal_block_length(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fs.mds.GetBlockInfoResponse)
  return target;
}

size_t GetBlockInfoResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fs.mds.GetBlockInfoResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string storage_addr = 2;
  if (this->storage_addr().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_storage_addr());
  }

  // uint64 volume_id = 3;
  if (this->volume_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_volume_id());
  }

  // uint64 block_offset = 4;
  if (this->block_offset() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_block_offset());
  }

  // uint64 block_length = 5;
  if (this->block_length() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_block_length());
  }

  // .fs.common.StatusCode status = 1;
  if (this->status() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_status());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetBlockInfoResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:fs.mds.GetBlockInfoResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const GetBlockInfoResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GetBlockInfoResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:fs.mds.GetBlockInfoResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:fs.mds.GetBlockInfoResponse)
    MergeFrom(*source);
  }
}

void GetBlockInfoResponse::MergeFrom(const GetBlockInfoResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fs.mds.GetBlockInfoResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.storage_addr().size() > 0) {
    _internal_set_storage_addr(from._internal_storage_addr());
  }
  if (from.volume_id() != 0) {
    _internal_set_volume_id(from._internal_volume_id());
  }
  if (from.block_offset() != 0) {
    _internal_set_block_offset(from._internal_block_offset());
  }
  if (from.block_length() != 0) {
    _internal_set_block_length(from._internal_block_length());
  }
  if (from.status() != 0) {
    _internal_set_status(from._internal_status());
  }
}

void GetBlockInfoResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:fs.mds.GetBlockInfoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetBlockInfoResponse::CopyFrom(const GetBlockInfoResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fs.mds.GetBlockInfoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetBlockInfoResponse::IsInitialized() const {
  return true;
}

void GetBlockInfoResponse::InternalSwap(GetBlockInfoResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  storage_addr_.Swap(&other->storage_addr_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetBlockInfoResponse, status_)
      + sizeof(GetBlockInfoResponse::status_)
      - PROTOBUF_FIELD_OFFSET(GetBlockInfoResponse, volume_id_)>(
          reinterpret_cast<char*>(&volume_id_),
          reinterpret_cast<char*>(&other->volume_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GetBlockInfoResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

MdsService::~MdsService() {}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* MdsService::descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_mds_2eproto);
  return file_level_service_descriptors_mds_2eproto[0];
}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* MdsService::GetDescriptor() {
  return descriptor();
}

void MdsService::RegisterNode(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::fs::mds::RegisterNodeRequest*,
                         ::fs::mds::RegisterNodeResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method RegisterNode() not implemented.");
  done->Run();
}

void MdsService::CreateFile(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::fs::mds::CreateFileRequest*,
                         ::fs::mds::CreateFileResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method CreateFile() not implemented.");
  done->Run();
}

void MdsService::Lookup(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::fs::mds::LookupRequest*,
                         ::fs::mds::LookupResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method Lookup() not implemented.");
  done->Run();
}

void MdsService::GetBlockInfo(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::fs::mds::GetBlockInfoRequest*,
                         ::fs::mds::GetBlockInfoResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method GetBlockInfo() not implemented.");
  done->Run();
}

void MdsService::CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                             ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                             const ::PROTOBUF_NAMESPACE_ID::Message* request,
                             ::PROTOBUF_NAMESPACE_ID::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), file_level_service_descriptors_mds_2eproto[0]);
  switch(method->index()) {
    case 0:
      RegisterNode(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::fs::mds::RegisterNodeRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::fs::mds::RegisterNodeResponse*>(
                 response),
             done);
      break;
    case 1:
      CreateFile(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::fs::mds::CreateFileRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::fs::mds::CreateFileResponse*>(
                 response),
             done);
      break;
    case 2:
      Lookup(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::fs::mds::LookupRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::fs::mds::LookupResponse*>(
                 response),
             done);
      break;
    case 3:
      GetBlockInfo(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::fs::mds::GetBlockInfoRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::fs::mds::GetBlockInfoResponse*>(
                 response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& MdsService::GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::fs::mds::RegisterNodeRequest::default_instance();
    case 1:
      return ::fs::mds::CreateFileRequest::default_instance();
    case 2:
      return ::fs::mds::LookupRequest::default_instance();
    case 3:
      return ::fs::mds::GetBlockInfoRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& MdsService::GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::fs::mds::RegisterNodeResponse::default_instance();
    case 1:
      return ::fs::mds::CreateFileResponse::default_instance();
    case 2:
      return ::fs::mds::LookupResponse::default_instance();
    case 3:
      return ::fs::mds::GetBlockInfoResponse::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

MdsService_Stub::MdsService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
MdsService_Stub::MdsService_Stub(
    ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
    ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::PROTOBUF_NAMESPACE_ID::Service::STUB_OWNS_CHANNEL) {}
MdsService_Stub::~MdsService_Stub() {
  if (owns_channel_) delete channel_;
}

void MdsService_Stub::RegisterNode(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::fs::mds::RegisterNodeRequest* request,
                              ::fs::mds::RegisterNodeResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}
void MdsService_Stub::CreateFile(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::fs::mds::CreateFileRequest* request,
                              ::fs::mds::CreateFileResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(1),
                       controller, request, response, done);
}
void MdsService_Stub::Lookup(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::fs::mds::LookupRequest* request,
                              ::fs::mds::LookupResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(2),
                       controller, request, response, done);
}
void MdsService_Stub::GetBlockInfo(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::fs::mds::GetBlockInfoRequest* request,
                              ::fs::mds::GetBlockInfoResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(3),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace mds
}  // namespace fs
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::fs::mds::RegisterNodeRequest* Arena::CreateMaybeMessage< ::fs::mds::RegisterNodeRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fs::mds::RegisterNodeRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::fs::mds::RegisterNodeResponse* Arena::CreateMaybeMessage< ::fs::mds::RegisterNodeResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fs::mds::RegisterNodeResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::fs::mds::CreateFileRequest* Arena::CreateMaybeMessage< ::fs::mds::CreateFileRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fs::mds::CreateFileRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::fs::mds::CreateFileResponse* Arena::CreateMaybeMessage< ::fs::mds::CreateFileResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fs::mds::CreateFileResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::fs::mds::LookupRequest* Arena::CreateMaybeMessage< ::fs::mds::LookupRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fs::mds::LookupRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::fs::mds::LookupResponse* Arena::CreateMaybeMessage< ::fs::mds::LookupResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fs::mds::LookupResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::fs::mds::GetBlockInfoRequest* Arena::CreateMaybeMessage< ::fs::mds::GetBlockInfoRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fs::mds::GetBlockInfoRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::fs::mds::GetBlockInfoResponse* Arena::CreateMaybeMessage< ::fs::mds::GetBlockInfoResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fs::mds::GetBlockInfoResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
